titleAndCommits: true
allowMergeCommits: true
allowRevertCommits: true

types:
  - "feat"
  - "fix"
  - "docs"
  - "style"
  - "refactor"
  - "perf"
  - "test"
  - "revert"
  - "version"

scopes:
  - "alpine"
  - "buster"
  - "stretch"
