FROM golang:1.14.4-buster

# Update registry otherwise unzip will not be found.
RUN apt-get update -y

# Install unzip.
RUN apt-get install unzip -y

# Enable Go modules.
ENV GO111MODULE on

# Set Blacksmith environment variables.
ENV BLACKSMITH_ENV docker-buster
ENV BLACKSMITH_VERSION v0.10.2

# Create the required directories.
RUN mkdir -p /.blacksmith/plugins/${BLACKSMITH_VERSION} && \
  mkdir -p /.blacksmith/scripts

# Copy the script files to the container.
COPY ./scripts /.blacksmith/scripts

# Download the adapters using the script.
RUN /.blacksmith/scripts/download-adapters.sh buster ${BLACKSMITH_VERSION}
